spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:${PORT}/${DATABASENAME}?serverTimezone=Asia/Seoul
    username: ${ROOT}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: postgresql
   # database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
